formation_index:
    path:     /
    defaults: { _controller: "FormationBundle:Formation:index" }
    methods:  GET

formation_show:
    path:     /{ref}/show
    defaults: { _controller: "FormationBundle:Formation:show" }
    methods:  GET

formation_new:
    path:     /new
    defaults: { _controller: "FormationBundle:Formation:new" }
    methods:  [GET, POST]

formation_edit:
    path:     /{ref}/edit
    defaults: { _controller: "FormationBundle:Formation:edit" }
    methods:  [GET, POST]

formation_delete:
    path:     /{ref}/delete
    defaults: { _controller: "FormationBundle:Formation:delete" }
    methods:  DELETE
